version: "3.8"
services:
  nodejs:
    container_name: nodejs_puppeteer_server
    build:
      dockerfile: Dockerfile
      context: ./
    ports:
     - "8080:8080"
    networks:
      - puppeteer-network
networks:
  puppeteer-network:
    name: puppeteer-network